spring:
  application:
    name: areumdap-be

  profiles:
    default: dev

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "<< Flyway Baseline >>"
#    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
